### ISSUE TITLE
Build doesn't work since today's changes

### ISSUE THREAD

**Issue by Lominatrix** [aloisdeniel/vsts-flutter-tasks#52]
Hello, Flutter install fails ever since the latest changes that happened 2 hours ago. Any idea?

Starting: Flutter Install
==============================================================================
Task         : Flutter Install
Description  : Install the Flutter environment.
Version      : 0.2.30
Author       : Aloïs Deniel
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
/Users/runner/runners/2.166.4/work/_tasks/FlutterInstall_fca8d27d-85f4-4d5d-a519-8d7a7edf15d7/0.2.30/node_modules/bent/src/nodejs.js:82
  res.json = async () => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/runner/runners/2.166.4/work/_tasks/FlutterInstall_fca8d27d-85f4-4d5d-a519-8d7a7edf15d7/0.2.30/index.js:14:14)
##[error]Exit code 1 returned from process: file name '/Users/runner/runners/2.166.4/externals/node/bin/node', arguments '"/Users/runner/runners/2.166.4/work/_tasks/FlutterInstall_fca8d27d-85f4-4d5d-a519-8d7a7edf15d7/0.2.30/index.js"'.
Finishing: Flutter Install

**Comment by DavidFD005** [comment]
Yes.. It doesn't work

**Comment by Sar777** [comment]
yeah, it is not working...

**Comment by Maricha** [comment]
Why this plugin doesn't have versions? One bad commit and every project is down

**Comment by rcharlier-delipay** [comment]
@aloisdeniel do you have any idea about the fix deployment? Bug is really impacting right now ..
Thank you in advance !

**Comment by FlorisDevreese** [comment]
Same issue here. Is there any way you can revert back to an old version
v0.2.15 worked for me

**Comment by INDAPP** [comment]
Same issue

**Comment by alexaniko88** [comment]
Same problem here!

**Comment by mweinand** [comment]
Same, please fix!

**Comment by aloisdeniel** [comment]
It seems to be a dependency that doesn't work on the agent ...

**Comment by GerardUmbert** [comment]
Same happens for me, any simpler solution with no upgrades of everything?

**Comment by aloisdeniel** [comment]
I published a new version without any dependency for http request that just fix the issue.

Let me know if it works for you!

**Comment by FlorisDevreese** [comment]
Hi @aloisdeniel,

I tried this pipeline
```yml
  - task: FlutterInstall@0
    displayName: Install Flutter
    inputs:
      channel: 'stable'
      version: 'custom'
      customVersion: '1.12.13+hotfix.9'
```

and got his error: `Cannot read property 'version' of undefined`

```log
2020-05-08T16:42:08.8602210Z ##[debug]Evaluating condition for step: 'Install Flutter'
2020-05-08T16:42:08.8603380Z ##[debug]Evaluating: SucceededNode()
2020-05-08T16:42:08.8603850Z ##[debug]Evaluating SucceededNode:
2020-05-08T16:42:08.8604380Z ##[debug]=> True
2020-05-08T16:42:08.8604950Z ##[debug]Result: True
2020-05-08T16:42:08.8605530Z ##[section]Starting: Install Flutter
2020-05-08T16:42:08.8612420Z ==============================================================================
2020-05-08T16:42:08.8612810Z Task         : Flutter Install
2020-05-08T16:42:08.8613080Z Description  : Install the Flutter environment.
2020-05-08T16:42:08.8613380Z Version      : 0.2.32
2020-05-08T16:42:08.8613590Z Author       : AloÃ¯s Deniel
2020-05-08T16:42:08.8614100Z Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
2020-05-08T16:42:08.8614570Z ==============================================================================
2020-05-08T16:42:09.0295400Z ##[debug]agent.TempDirectory=/Users/runner/runners/2.166.4/work/_temp
2020-05-08T16:42:09.0317510Z ##[debug]loading inputs and endpoints
2020-05-08T16:42:09.0323050Z ##[debug]loading INPUT_CHANNEL
2020-05-08T16:42:09.0354220Z ##[debug]loading INPUT_VERSION
2020-05-08T16:42:09.0358640Z ##[debug]loading INPUT_CUSTOMVERSION
2020-05-08T16:42:09.0360950Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-05-08T16:42:09.0363010Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-05-08T16:42:09.0366270Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-05-08T16:42:09.0374080Z ##[debug]loading SECRET_IOS-DISTRIBUTION_P12-PASSWORD
2020-05-08T16:42:09.0377130Z ##[debug]loading SECRET_ANDROIDKEYSTOREPASSWORD
2020-05-08T16:42:09.0378450Z ##[debug]loading SECRET_KEYCHAINPASSWORD
2020-05-08T16:42:09.0381300Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2020-05-08T16:42:09.0384150Z ##[debug]loading SECRET_IOS_DEVELOPMENT_P12-PASSWORD
2020-05-08T16:42:09.0385720Z ##[debug]loading SECRET_ANDROIDKEYSTOREKEYPASSWORD
2020-05-08T16:42:09.0388210Z ##[debug]loaded 12
2020-05-08T16:42:09.0407490Z ##[debug]Agent.ProxyUrl=undefined
2020-05-08T16:42:09.0408670Z ##[debug]Agent.CAInfo=undefined
2020-05-08T16:42:09.0410300Z ##[debug]Agent.ClientCert=undefined
2020-05-08T16:42:09.0413480Z ##[debug]Agent.SkipCertValidation=undefined
2020-05-08T16:42:09.0495330Z ##[debug]Agent.ProxyUrl=undefined
2020-05-08T16:42:09.0497060Z ##[debug]Agent.CAInfo=undefined
2020-05-08T16:42:09.0497840Z ##[debug]Agent.ClientCert=undefined
2020-05-08T16:42:09.0502120Z ##[debug]check path : /Users/runner/runners/2.166.4/work/_tasks/FlutterInstall_fca8d27d-85f4-4d5d-a519-8d7a7edf15d7/0.2.32/node_modules/azure-pipelines-tool-lib/lib.json
2020-05-08T16:42:09.0504320Z ##[debug]adding resource file: /Users/runner/runners/2.166.4/work/_tasks/FlutterInstall_fca8d27d-85f4-4d5d-a519-8d7a7edf15d7/0.2.32/node_modules/azure-pipelines-tool-lib/lib.json
2020-05-08T16:42:09.0505380Z ##[debug]system.culture=en-US
2020-05-08T16:42:09.0540870Z ##[debug]channel=stable
2020-05-08T16:42:09.0544840Z ##[debug]version=custom
2020-05-08T16:42:09.0546710Z ##[debug]customVersion=1.12.13+hotfix.9
2020-05-08T16:42:09.1384910Z statusCode: 200
2020-05-08T16:42:09.1553110Z ##[debug]task result: Failed
2020-05-08T16:42:09.1605130Z ##[error]TypeError: Cannot read property 'version' of undefined
2020-05-08T16:42:09.1619240Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'version' of undefined
2020-05-08T16:42:09.1631370Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'version' of undefined
2020-05-08T16:42:09.1634430Z ##[section]Finishing: Install Flutter
```

When I run it with the latest flutter version instead of `v1.12.13+hotfix.9`, then it works 😁
```yml
  - task: FlutterInstall@0
    displayName: Install Flutter
    inputs:
      channel: 'stable'
      version: 'latest'
```

Hope this helps!


FYI: I run it on the macOS-10.15 VM agent
```yml
pool:
  vmImage: "macOS-10.15"
```

**Comment by hectorvillag** [comment]
Same issue

**Comment by aloisdeniel** [comment]
It seems that distant requests are failing on hosted agents, while working well on local machines.

I just published a version based on curl. Not the prettiest solution, but let's hope it fixes the issue.

**Comment by aloisdeniel** [comment]
And for those who wonder about Azure Pipeline development, it is a real pain! You have different behaviours on hosted agents. 

So sorry but I'm alone maintaining all of this, you can host your own extensions if you want to be sure of the stability. 

Ideally, Microsoft would maintain this one day, when Xamarin will become obsolete. :)

**Comment by chadrickman** [comment]
I'm still getting this error. `##[error]TypeError: Cannot read property 'version' of undefined`.
```
==============================================================================
Task         : Flutter Install
Description  : Install the Flutter environment.
Version      : 0.2.33
Author       : Aloïs Deniel
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
```

**Comment by hectorvillag** [comment]
> ```yaml
> 1.12.13+hotfix.9
> ```

I resolved this issue adding the v to the version string  `v1.12.13+hotfix.9`

**Comment by chadrickman** [comment]
Thanks @hectorvillag that seems to have done the trick 🎉

**Comment by chadrickman** [comment]
Dropping this here in case anyone else runs into this. The `Tests` tasks is failing on publishing of results now as well. I've spun up a issue over at #54 if anyone else is having this issue.

**Comment by aloisdeniel** [comment]
Thanks a lot @hectorvillag.

I see why now, there's a prefix in the history file. I added the node request logic and added a check to uniformize all version numbers by removing that `v` prefix.

I hope we're finally good!

**Comment by skela** [comment]
Install works ok for us now but not test, there’s another issue raised already for that thought just wanted to clarify if it helps at all.

**Comment by aloisdeniel** [comment]
There is dedicated issue.

I’ll close this one, since it seems okay for people.
