### ISSUE TITLE
Flutter Install Failed on Ubuntu

### ISSUE THREAD

**Issue by Vayth** [aloisdeniel/vsts-flutter-tasks#56]
On ubuntu-latest agent, I got this error when executing Flutter Install.
```
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install
Description  : Install the Flutter environment.
Version      : 0.2.35
Author       : Aloïs Deniel
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
Downloading: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.17.1-stable.tar.xz
Extracting archive
/usr/bin/unzip /home/vsts/work/_temp/e606a105-28f8-4b64-9a04-8421883bf27c
Archive:  /home/vsts/work/_temp/e606a105-28f8-4b64-9a04-8421883bf27c

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/vsts/work/_temp/e606a105-28f8-4b64-9a04-8421883bf27c or
        /home/vsts/work/_temp/e606a105-28f8-4b64-9a04-8421883bf27c.zip, and cannot find /home/vsts/work/_temp/e606a105-28f8-4b64-9a04-8421883bf27c.ZIP, period.
##[error]Error: The process '/usr/bin/unzip' failed with exit code 9
Finishing: FlutterInstall
```

It runs normally on macos-latest. Not sure whether the linux package itself is broken or what, but I thought I should ask here first.

**Comment by ced455** [comment]
same issue here

**Comment by Max-Might** [comment]
Same issue :(

Is there any workaround for this? Using different ubuntu version or flutter version?

**Comment by Max-Might** [comment]
@aloisdeniel I think I found the problem.
Flutter uses `ZIP` files for Mac and Windows releases and `Tar` files for linux.

[This](https://github.com/aloisdeniel/vsts-flutter-tasks/blob/4f252baada040c803c6b41c1501e5042b05c72c0/tasks/install/index.ts#L90) has to be changed to use [tool.extractTar()](https://github.com/microsoft/azure-pipelines-tool-lib/blob/c460d77d4b8c5a91da128b05e1b01babcdafb616/tool.ts#L443) for Linux builds.

This will enable the extension to be used on Linux build runners.

**Comment by Max-Might** [comment]
So I opened pull request #57 that should fix the issue.
I did not test it though.

**Comment by hey24sheep** [comment]
Fixed it on [mine](https://github.com/hey24sheep/vsts-flutter-tasks) I do not have a linux pipeline. You could test and let me know. Credit to @Max-Might

**Comment by Vayth** [comment]
Thanks, @hey24sheep . Unfortunately, for some strange reason, my pipeline keep using version 0.2.34 even though I have installed latest (0.2.35) and it still failed.

However, looking at your code, seems like you still use the zip path. Maybe you should refer to flutter json like the one used in alois' fix of path issue back then ( http://storage.googleapis.com/flutter_infra/releases/releases_$(arch).json )

By the way, I couldn't find issue tab on your repo, so do we just report yours here as well? It'd be better if you could become a maintainer here too so we don't have multiple extension.

**Comment by hey24sheep** [comment]
@Vayth You couldn't update your pipeline maybe b'cuz you are using Alois's extension. I will look into the zip path, and fix it. 

> By the way, I couldn't find issue tab on your repo, so do we just report yours here as well? It'd be better if you could become a maintainer here too so we don't have multiple extension.

I have my own extension, there are a few reasons. Alois is busy, and I have seen issues pending for months here. Also, We use this extension in our builds and my boss said to have our own for future sake. So, best way to keep our builds successful is to have our own extension which if even fails we can fix asap. Also, I do not want to throw my updates on existing users and break their builds.

I have intentionally forked this repo to keep credits to people and transparency. I know there is no issue page but PRs are always welcome :) and I don't think I can be a maintainer here, because I opened an issue here months ago and I said the same thing. But, it was stale and then closed by owner after I created mine. Like your own issue is May 14 and its been a month. In production environment it's difficult to depend on 3rd party. I hope you understand my view.

**Comment by Vayth** [comment]
No, I was using your fork in my test org and verified it to be 0.2.35, yet the one in pipeline run log showed 0.2.34. I think pipeline need some time to adjust the version. Now it's correctly state 0.2.35.

However, I still have problem extracting it.
```
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.2.35
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3656) Warning: Use Cipheriv for counter mode of aes-256-ctr
Downloading: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.17.3-stable.tar.xz
Extracting archive
/bin/tar xzC /home/vsts/work/_temp/25177519-c871-42ee-9a0b-bb68d8475311 -f /home/vsts/work/_temp/1c6e50c0-2e07-43ca-b748-8f7a3de5f6bd

gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
##[error]Error: /bin/tar failed with return code: 2
Finishing: FlutterInstall
```

I believe it should use `tar -xf` instead of `tar -xzf` like in the log.

**Comment by hey24sheep** [comment]
@Vayth I don't think we can change those args, there is no option. Here is the [code for extractZip](https://github.com/microsoft/azure-pipelines-tool-lib/blob/f9220e34b9aea8e4241fee20df2452e55142cb47/tool.ts#L452)

**Comment by hey24sheep** [comment]
@Vayth I have updated my extension, let me know if it works now. I have changed extract to 7z as per [wiki](https://en.wikipedia.org/wiki/7-Zip) it supports .xz and tar. So, it should work now.

**Comment by Max-Might** [comment]
From the extract7z() implementation:

```typescript
if (process.platform != 'win32') {
    throw new Error('extract7z() not supported on current OS');
}
```

So this will work only on windows hosts, unfortunately (if it works, I can't test it).

**Comment by Max-Might** [comment]
@hey24sheep @Vayth  OK, it looks like [someone just removed](https://github.com/microsoft/azure-pipelines-tool-lib/commit/e49dba27aa56622b6aa3118d95be48bd78ba0c0d) the `z` flag from the tool function and `extractTar()` should work now with the `tar.xz` file.

**Comment by hey24sheep** [comment]
Hi, @Max-Might I see. But, they haven't released the update on [npm yet ](https://github.com/microsoft/azure-pipelines-tool-lib/issues/54)

**Comment by stephenmichaelf** [comment]
@hey24sheep We have now released the lib.

**Comment by hey24sheep** [comment]
@stephenmichaelf Yayy, Thanks 👍 

@Vayth Try now its fixed pushed.

**Comment by Vayth** [comment]
Alright, it's installed and built successfully. Thanks a lot, @hey24sheep , @Max-Might , @stephenmichaelf !

Now I wonder if this issue should be closed or not, since alois' version _here_ is not fixed yet.

**Comment by Max-Might** [comment]
@Vayth Yep, I updated my PR to use the new version of the azure pipelines tool lib. Now it is up to @aloisdeniel to review it when he has some spare time. Thanks for testing the changes.

**Comment by hey24sheep** [comment]
Thanks everyone

**Comment by Nash0x7E2** [comment]
This appears to still be occurring. Encountered while trying to install the latest dev version. 

Error:
```bash 
unzip:  cannot find zipfile directory in one of /home/vsts/work/_temp/02249d3f-cd47-4be0-a418-7064fbfe6e92 or
        /home/vsts/work/_temp/02249d3f-cd47-4be0-a418-7064fbfe6e92.zip, and cannot find /home/vsts/work/_temp/02249d3f-cd47-4be0-a418-7064fbfe6e92.ZIP, period
```

**Comment by Max-Might** [comment]
@Nash0x7E2 There is a pending PR #57 that fixes the issue.
We need @aloisdeniel or someone else who has permission to merge it can do it and upload it.

**Comment by hey24sheep** [comment]
@Nash0x7E2 you could use [my ext](https://github.com/hey24sheep/vsts-flutter-tasks) for the time being if you want. I do not know when it will be fixed here. If the issue exists on my fork as well, let me know.

**Comment by Nash0x7E2** [comment]
Thanks @hey24sheep! Is it possible to add support for master on your fork? Building for web is currently not supported on dev :/

**Comment by hey24sheep** [comment]
@Nash0x7E2 I have master on my fork. There is no dev branch.

> Building for web is currently not supported on dev :/

What do you mean by this?

**Comment by Nash0x7E2** [comment]
@hey24sheep I mean installing Flutter from the master channel and building Flutter web

**Comment by hey24sheep** [comment]
But you could just download the extension on your azure account and it will work. @Nash0x7E2 and I already have master channel and it works. I don't understand what you want to do

**Comment by elpablete** [comment]
Any update on the "official vsts task"? or I'm not understanding which version is the "official" between @hey24sheep 's and @aloisdeniel 's ?

**Comment by hey24sheep** [comment]
@elpablete this one is original but not maintained repository. I have the fork which I maintain. I have been asked to make my fork into a separate repository but I have not done it because of different reasons it's been discussed on my fork issues section
